mybatis:
  configuration:
    map-underscore-to-camel-case: true
spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  shardingsphere:
    database:
      name: "sharding_db"
    datasource:
      names: ds-0
      ds-0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: org.h2.Driver
        jdbc-url: jdbc:h2:mem:master;MODE=MYSQL;DATABASE_TO_LOWER=TRUE;INIT=RUNSCRIPT FROM 'classpath:db/t_order.sql'
        username: sa
        password: ""
    rules:
      sharding:
        tables:
          t_order:
            actual-data-nodes: ds-0.t_order_$->{20221123..20221125}
            tableStrategy:
              standard:
                sharding-column: create_time
                sharding-algorithm-name: lingh-interval
        sharding-algorithms:
          lingh-interval:
            type: INTERVAL
            props:
              datetime-pattern: "yyyy-MM-dd HH:mm:ss.SSS"
              datetime-lower: "2022-11-23 00:00:00.000"
              datetime-upper: "2022-11-26 00:00:00.000"
              sharding-suffix-pattern: "_yyyyMMdd"
              datetime-interval-amount: 1
              datetime-interval-unit: "DAYS"