databaseName: sharding_db

dataSources:
  ds-0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: org.h2.Driver
    jdbcUrl: jdbc:h2:mem:master;MODE=MYSQL;INIT=RUNSCRIPT FROM 'classpath:db/t_order.sql'
    username: sa
    password:

rules:
- !SHARDING
  tables:
    t_order:
      actualDataNodes: ds-0.t_order_$->{20221123..20221125}
      tableStrategy:
        standard:
          shardingColumn: create_time
          shardingAlgorithmName: lingh_interval
  shardingAlgorithms:
    lingh_interval:
      type: INTERVAL
      props:
        datetime-pattern: "yyyy-MM-dd HH:mm:ss.SSS"
        datetime-lower: "2022-11-23 00:00:00.000"
        datetime-upper: "2022-11-26 00:00:00.000"
        sharding-suffix-pattern: "_yyyyMMdd"
        datetime-interval-amount: 1
        datetime-interval-unit: "DAYS"
- !SINGLE
  tables:
    - "*.*"

